1.java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "this.pool" is null,没有初始化，所以pool.size() < MAX这里的list是空，报错了，那就初始化一下，测试通过